listener_port=4444
logdir=~/.tmuxer/logs
prepend_space=1
cmd_1_name="Quick Recon"
cmd_1="id; uname -a; hostname"
cmd_2_name="Full Recon"
cmd_2="id; uname -a; w; netstat -tulip; ip a; arp -a; ip r; ps ax"
